### ISSUE TITLE
change directory to ns-3.29

### ISSUE THREAD

**Issue by SpandanKumarSahu** [shreyase99/rest-tepo#1]
[this](https://github.com/shreyase99/rest-tepo/blob/c51309e726e14947415d72626eea3b6dcafa740b/ns3_dependies_and%20_setup.sh#L41) command fails, because the directory hasn't been changed to ns-3.29

**Comment by shreyase99** [comment]
https://github.com/shreyase99/rest-tepo/commit/6090e9858fd29e9962d806703298a0e28d9d7702

Thank you for raising this issue. I just noticed this!
Made the changes.

**Comment by shreyase99** [comment]
> [6090e98](https://github.com/shreyase99/rest-tepo/commit/6090e9858fd29e9962d806703298a0e28d9d7702)
> 
> Thank you for raising this issue. I just noticed this!
> Made the changes.

I had made another mistake while correcting. corrected it.
https://github.com/shreyase99/rest-tepo/commit/767fa4c52755fae7cc08c06eac2b229633fadb43
